name = "SodShockTube"
uuid = "2160a001-e9fc-4c63-b529-f2c7ec8d982c"
authors = ["Thomas Marks <marksta@umich.edu> and contributors"]
version = "1.0.2"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
PartialFunctions = "570af359-4316-4cb7-8c74-252c00c2016b"

[compat]
NLsolve = "4"
PartialFunctions = "1"
julia = "1.6"
